In [3]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("marksheet.csv")
print(df)

      id      Name  Gender  Age Section  Science  English  History  Maths
0      1   Bronnie  Female   13       C       21       81       62     49
1      2    Lemmie    Male   15       B       29       41       17     40
2      3     Danya  Female   14       C       12       87       16     96
3      4     Denna  Female   14       B       15       53       82     33
4      5   Jocelin    Male   14       A       43        6        3     21
..   ...       ...     ...  ...     ...      ...      ...      ...    ...
245  246    Nickie    Male   13       C       28       15       25     10
246  247       Rog  Female   13       B        1        4       68     65
247  248      Kaia    Male   15       B       93       48       82     44
248  249      Anni  Female   14       B       35       73       66     59
249  250  Fernande    Male   15       B       50        8       80     78

[250 rows x 9 columns]

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       250 non-null    int64
 1   Name     250 non-null    str
 2   Gender   250 non-null    str
 3   Age      250 non-null    int64
 4   Section  250 non-null    str
 5   Science  250 non-null    int64
 6   English  250 non-null    int64
 7   History  250 non-null    int64
 8   Maths    250 non-null    int64
dtypes: int64(6), str(3)
memory usage: 17.7 KB

In [6]:
df.head()

   id     Name  Gender  Age Section  Science  English  History  Maths
0   1  Bronnie  Female   13       C       21       81       62     49
1   2   Lemmie    Male   15       B       29       41       17     40
2   3    Danya  Female   14       C       12       87       16     96
3   4    Denna  Female   14       B       15       53       82     33
4   5  Jocelin    Male   14       A       43        6        3     21

In [7]:
df.describe()

               id         Age     Science     English     History       Maths
count  250.000000  250.000000  250.000000  250.000000  250.000000  250.000000
mean   125.500000   14.020000   51.440000   47.980000   52.272000   53.016000
std     72.312977    0.823598   29.314497   29.949013   26.868526   27.386416
min      1.000000   13.000000    1.000000    1.000000    1.000000    1.000000
25%     63.250000   13.000000   25.250000   20.250000   31.000000   30.000000
50%    125.500000   14.000000   53.000000   47.500000   53.000000   52.500000
75%    187.750000   15.000000   78.000000   74.000000   76.000000   76.000000
max    250.000000   15.000000  100.000000  100.000000  100.000000  100.000000

In [8]:
#observation from science
#25% ----> 25% students scored below 25.25 -----> weak group (0-30)
#50% ----> 50% students scored below 53 ----> below average(30-55)
# 75% ---> 75% students scored below 78 ---> average to good

# helps to understand distribution and performance of groups 

#mean == median ----> balanced/symmetric data
#mean>> median ---> right skew
##mean<<median --->left skew
# one large value (eg : 200) is pulling mean up

#mean << median -----> left skew
#   if extreme low increases

# median is important because eg: if some students score extremely high or low

#eg: 
#mean = 51.44
#median = 53

# no extreme distortion so data is balanced

In [9]:
# std = standard deviation
# it measures "how spread out the value(marks) are "

#45,48,50,52,55
# mean ~ 50
#sd will be low

#10,30,50,70,100
#   mean ~ 50
# sd will be high

In [10]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])
df

      id      Name  Gender  Age Section  Science  English  History  Maths
0      1   Bronnie       0   13       C       21       81       62     49
1      2    Lemmie       1   15       B       29       41       17     40
2      3     Danya       0   14       C       12       87       16     96
3      4     Denna       0   14       B       15       53       82     33
4      5   Jocelin       1   14       A       43        6        3     21
..   ...       ...     ...  ...     ...      ...      ...      ...    ...
245  246    Nickie       1   13       C       28       15       25     10
246  247       Rog       0   13       B        1        4       68     65
247  248      Kaia       1   15       B       93       48       82     44
248  249      Anni       0   14       B       35       73       66     59
249  250  Fernande       1   15       B       50        8       80     78

[250 rows x 9 columns]

In [11]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Section']=le.fit_transform(df['Section'])
df

      id      Name  Gender  Age  Section  Science  English  History  Maths
0      1   Bronnie       0   13        2       21       81       62     49
1      2    Lemmie       1   15        1       29       41       17     40
2      3     Danya       0   14        2       12       87       16     96
3      4     Denna       0   14        1       15       53       82     33
4      5   Jocelin       1   14        0       43        6        3     21
..   ...       ...     ...  ...      ...      ...      ...      ...    ...
245  246    Nickie       1   13        2       28       15       25     10
246  247       Rog       0   13        1        1        4       68     65
247  248      Kaia       1   15        1       93       48       82     44
248  249      Anni       0   14        1       35       73       66     59
249  250  Fernande       1   15        1       50        8       80     78

[250 rows x 9 columns]

In [ ]:
#heatmap

#A heatmap uses colors to represents to represents numerical values in a table/matrix

# When the values are high, low or showing a patterns across two dimensions